language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

script:
  - ./tests/run.sh

install:
  - composer install --dev

before_install:
  - composer self-update